# 1.4.4 Smoothing Images

## Kernel Convolution

In [78]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [79]:
l=1
kernel = np.array([[1,4,6,4,1],[4,16,24,16,4],[6,24,-476,24,6],[4,16,24,16,4],[1,4,6,4,1]],np.float32)/-256

In [80]:
kernel

array([[-0.00390625, -0.015625  , -0.0234375 , -0.015625  , -0.00390625],
       [-0.015625  , -0.0625    , -0.09375   , -0.0625    , -0.015625  ],
       [-0.0234375 , -0.09375   ,  1.859375  , -0.09375   , -0.0234375 ],
       [-0.015625  , -0.0625    , -0.09375   , -0.0625    , -0.015625  ],
       [-0.00390625, -0.015625  , -0.0234375 , -0.015625  , -0.00390625]],
      dtype=float32)

In [81]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [82]:
img

array([[0, 3, 1, 5, 4, 8, 1, 4, 0, 9, 0, 4],
       [4, 2, 0, 7, 1, 6, 9, 5, 3, 3, 0, 0],
       [9, 5, 3, 2, 0, 8, 1, 8, 7, 3, 7, 1],
       [8, 0, 8, 8, 1, 5, 5, 7, 9, 8, 5, 4],
       [1, 1, 9, 2, 6, 6, 3, 0, 4, 2, 7, 7],
       [9, 5, 0, 8, 5, 8, 7, 9, 1, 1, 7, 7],
       [6, 4, 9, 0, 7, 8, 6, 8, 8, 2, 2, 7],
       [1, 8, 5, 1, 3, 6, 0, 2, 5, 4, 7, 3],
       [8, 2, 0, 3, 0, 3, 2, 3, 2, 7, 4, 5],
       [4, 2, 7, 4, 4, 3, 1, 0, 8, 4, 2, 5],
       [8, 7, 0, 4, 2, 1, 2, 5, 7, 5, 8, 6],
       [5, 4, 8, 1, 5, 8, 2, 6, 4, 3, 1, 4]])

In [83]:
h,w=img.shape

In [84]:
print(h,w)

12 12


In [85]:
#[*range(-2,3)]

In [86]:
dst = np.zeros((h,w),np.int)

C:\Users\U\AppData\Local\Temp\ipykernel_13524\2160328971.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dst = np.zeros((h,w),np.int)


In [87]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [88]:
img

array([[0, 3, 1, 5, 4, 8, 1, 4, 0, 9, 0, 4],
       [4, 2, 0, 7, 1, 6, 9, 5, 3, 3, 0, 0],
       [9, 5, 3, 2, 0, 8, 1, 8, 7, 3, 7, 1],
       [8, 0, 8, 8, 1, 5, 5, 7, 9, 8, 5, 4],
       [1, 1, 9, 2, 6, 6, 3, 0, 4, 2, 7, 7],
       [9, 5, 0, 8, 5, 8, 7, 9, 1, 1, 7, 7],
       [6, 4, 9, 0, 7, 8, 6, 8, 8, 2, 2, 7],
       [1, 8, 5, 1, 3, 6, 0, 2, 5, 4, 7, 3],
       [8, 2, 0, 3, 0, 3, 2, 3, 2, 7, 4, 5],
       [4, 2, 7, 4, 4, 3, 1, 0, 8, 4, 2, 5],
       [8, 7, 0, 4, 2, 1, 2, 5, 7, 5, 8, 6],
       [5, 4, 8, 1, 5, 8, 2, 6, 4, 3, 1, 4]])

In [89]:
dst

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  2,  0, 13,  0, 13, 11,  3, 12,  0,  0],
       [ 0, 13, 13,  0,  8,  7, 11, 14, 12,  7,  6,  0],
       [ 0, 15,  1,  9,  9,  3, -1,  5,  1, 11, 11,  0],
       [ 0, -1, 13,  7, 13, 11, 15,  0,  0, 11, 11,  0],
       [ 0, 15, -1, 11, 12,  8, 12, 13,  2,  2, 11,  0],
       [ 0,  7,  0,  4,  9, -2,  1,  7,  6, 11,  3,  0],
       [ 0, -1,  4,  0,  4,  2,  4,  2, 11,  5,  7,  0],
       [ 0, 12,  6,  6,  4,  1,  0, 14,  5,  2,  7,  0],
       [ 0, -1,  6,  2,  0,  3,  8, 11,  7, 13,  9,  0],
       [ 0, 13,  0,  8, 13,  2, 10,  5,  3,  0,  5,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [90]:
img = cv2.imread('lena.png', 0)

In [91]:
h,w=img.shape

In [92]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [93]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [94]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()